### PR TITLE
added initialize feature of Dispatcher.

### PR DESCRIPTION
**Pull request by yoshimov**
I've added initialize feature for each command to do the background job like polling.
Could you consider to include this feature?

### CODE REVIEW

**Comment by wardellbagby** [comment]
I understand the feature, but I can't think of any situations where this could be a thing that's needed.

Do you have any specific command or command idea that could benefit from this initialization logic?

**Comment by yoshimov** [comment]
I've created a push notification bot to watch a log file.
I think it requires some startup code with bot object.

**Comment by cntrlwiz** [comment]
@yoshimov Is this for features like pinging another user?
or, for fault notification?

**Comment by wardellbagby** [comment]
While I like what you're trying to do with this, I'm not a big fan of the way it's went about.

I don't like the idea of the HangoutsBot object having a reference to the DispatcherSingleton; only the Handler should have that functionality. (I say this ignoring the current reference the HangoutsBot has to the Singleton, as it needs to be refactored and I put a note in there to that end.)

I have a few solutions for you that I would be much more approving of:
1. Do all your initialization logic in the same file that your commands are in. It will be ran whenever the file is imported. (Which is right after the HangoutsBot is connected and is creating the MessageHandler) This is assuming that you don't truly need a reference to the Bot, and only need to know that the Bot is connected.
2. Create a new annotation (perhaps @DispatcherSingleton.register_init?) and then the Dispatcher will call all of those when the MessageHandler is being initialized. That way, you can have a reference to the bot without having the bot know about the commands. 

But like @cntrlwiz said, it would be more helpful to know what you were doing to see if we could come up with a better solution for the bot overall.

Regardless, feel free to use whatever method you wish to in your own fork, but this is an interesting concept and I would like to implement it in the mine if we could all come into a good solution.

**Comment by yoshimov** [comment]
Thank you for your interest.

It is something like a fault notification and it is filtered using different rules for each conversations.
I prefer to take solution 2 because I would like to start the notification automatically.
I will fix the pull request to use MessageHandler for initializing.

**Comment by yoshimov** [comment]
i just updated my branch.

**Comment by yoshimov** [comment]
Is there any issue to fix?
I think the updated pull request follows your solution 2 suggestion.
Or just decide to discard this feature?

**Pull request closed without merging**
